//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SNRegistros.Dominio.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accione
    {
        public Accione()
        {
            this.RegistrosMedicos = new HashSet<RegistrosMedico>();
        }
    
        public int AccionID { get; set; }
        public string Nombre { get; set; }
        public int ProcesoID { get; set; }
    
        public virtual Proceso Proceso { get; set; }
        public virtual ICollection<RegistrosMedico> RegistrosMedicos { get; set; }
    }
}
