//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SNRegistros.Dominio.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ciudadade
    {
        public Ciudadade()
        {
            this.Comisarias = new HashSet<Comisaria>();
            this.Hospitales = new HashSet<Hospitale>();
        }
    
        public int CiudadID { get; set; }
        public string Nombre { get; set; }
        public int DepartamentoID { get; set; }
    
        public virtual ICollection<Comisaria> Comisarias { get; set; }
        public virtual ICollection<Hospitale> Hospitales { get; set; }
    }
}
