//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SNRegistros.Dominio.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcesosPoliciale
    {
        public ProcesosPoliciale()
        {
            this.AccionesPoliciales = new HashSet<AccionesPoliciale>();
        }
    
        public int ProcesoPolicialID { get; set; }
        public string NombrePP { get; set; }
    
        public virtual ICollection<AccionesPoliciale> AccionesPoliciales { get; set; }
    }
}
