//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SNRegistros.Dominio.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistrosJudiciale
    {
        public int RegistroJudicialID { get; set; }
        public int CiudadanoID { get; set; }
        public int FuncJudicialId { get; set; }
        public int JuzgadoID { get; set; }
        public int AccJudID { get; set; }
        public string Comentario { get; set; }
    
        public virtual AccionesJudiciale AccionesJudiciale { get; set; }
        public virtual Ciudadano Ciudadano { get; set; }
        public virtual FuncionariosJudiciale FuncionariosJudiciale { get; set; }
        public virtual Juzgado Juzgado { get; set; }
    }
}
