//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SNRegistros.Dominio.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistrosMedico
    {
        public int RegistroMedicoID { get; set; }
        public int Ciudadanoid { get; set; }
        public int MedicoID { get; set; }
        public int HospitalID { get; set; }
        public int AccionID { get; set; }
        public string Comentario { get; set; }
        public Nullable<System.DateTime> Momento { get; set; }
    
        public virtual Accione Accione { get; set; }
        public virtual Ciudadano Ciudadano { get; set; }
        public virtual Doctore Doctore { get; set; }
        public virtual Hospitale Hospitale { get; set; }
    }
}
