//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SNRegistros.Dominio.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistrosPoliciale
    {
        public int RegistroPolicialID { get; set; }
        public int CiudadanoID { get; set; }
        public int PoliciaID { get; set; }
        public int ComisariaID { get; set; }
        public int AccPolID { get; set; }
        public string Comentario { get; set; }
    
        public virtual AccionesPoliciale AccionesPoliciale { get; set; }
        public virtual Ciudadano Ciudadano { get; set; }
        public virtual Comisaria Comisaria { get; set; }
        public virtual Policia Policia { get; set; }
    }
}
