//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SNRegistros.Dominio.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SNRegistroEntities : DbContext
    {
        public SNRegistroEntities()
            : base("name=SNRegistroEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accione> Acciones { get; set; }
        public virtual DbSet<AccionesJudiciale> AccionesJudiciales { get; set; }
        public virtual DbSet<AccionesPoliciale> AccionesPoliciales { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Ciudadade> Ciudadades { get; set; }
        public virtual DbSet<Ciudadano> Ciudadanos { get; set; }
        public virtual DbSet<Comisaria> Comisarias { get; set; }
        public virtual DbSet<Departamento> Departamentos { get; set; }
        public virtual DbSet<Doctore> Doctores { get; set; }
        public virtual DbSet<FuncionariosJudiciale> FuncionariosJudiciales { get; set; }
        public virtual DbSet<Hospitale> Hospitales { get; set; }
        public virtual DbSet<Juzgado> Juzgados { get; set; }
        public virtual DbSet<Policia> Policias { get; set; }
        public virtual DbSet<Proceso> Procesos { get; set; }
        public virtual DbSet<ProcesosJudiciale> ProcesosJudiciales { get; set; }
        public virtual DbSet<ProcesosPoliciale> ProcesosPoliciales { get; set; }
        public virtual DbSet<RegistrosJudiciale> RegistrosJudiciales { get; set; }
        public virtual DbSet<RegistrosMedico> RegistrosMedicos { get; set; }
        public virtual DbSet<RegistrosPoliciale> RegistrosPoliciales { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
    }
}
